version: "3"
services:
  redis:
    image: "redis:latest"
    container_name: url_shortener_redis
    restart: always
    ports:
      - "16379:6379"
#  rust:
#    build: .
#    container_name: rust
#    restart: always
